module.exports={
	page:[
		{
			explain:'风电场集合风机部件页1',
			url:'main/tree/tab',
			pagetype:'定制页面',
			time:'2017-6-26',
			people:'赵虹乔',
		},
		{
			explain:'风电场集合风机部件页2',
			url:'main/tree/page2',
			pagetype:'组态页面',
			time:'2017-5-26',
			people:'薛旭东',
		},
		{
			explain:'风电场集合风机部件页3',
			url:'main/tree/page3',
			pagetype:'定制页面',
			time:'2017-5-14',
			people:'林津津',
		},
		{
			explain:'风电场集合风机部件页4',
			url:'main/tree/page4',
			pagetype:'组态页面',
			time:'2017-3-16',
			people:'杨媛媛',
		},
		{
			explain:'风电场集合风机部件页5',
			url:'main/tree/page5',
			pagetype:'定制页面',
			time:'2016-12-06',
			people:'路迪',
		},
		{
			explain:'风电场集合风机部件页6',
			url:'main/tree/page6',
			pagetype:'定制页面',
			time:'2017-4-18',
			people:'张一山',
		},
		{
			explain:'风电场集合风机部件页7',
			url:'main/tree/page7',
			pagetype:'定制页面',
			time:'2017-2-26',
			people:'张丹丹',
		},
		{
			explain:'风电场集合风机部件页8',
			url:'main/tree/page8',
			pagetype:'定制页面',
			time:'2015-11-26',
			people:'黄慧敏',
		},
	]
}