module.exports = [
 {
    name: '标题框',
    type: 'div',
    width: '2',
    height: '1',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/tit.png'),
  },
   {
    name: '卡片',
    type: 'card',
    width: '3',
    height: '3',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/card.png'),
  },
  {
    name: '饼图',
    type: 'pie',
    width: '3',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/piechart.png'),
  },
  {
    name: '环形图',
    type: 'annulus',
    width: '3',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/annulus.png'),
  },
  {
    name: '折线图',
    type: 'line',
    width: '6',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/line.png'),
  },
  {
    name: '柱状图',
    type: 'column',
    width: '6',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/column.png'),
  },
  {
    name: '复合图',
    type: 'coline',
    width: '6',
    height: '2',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/coline.png'),
  },
  {
    name: '条形图',
    type: 'bar',
    width: '6',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/bar.png'),
  },
  {
    name: '堆叠柱状图',
    type: 'stack',
    width: '6',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/stack.png'),
  },
  {
    name: '双y轴复合图',
    type: 'double',
    width: '6',
    height: '3',
    menutype:'chart',
    index:'1',
    imgurl:require('../../../img/coline.png'),
  },
  {
    name: '日期控件',
    type: 'datepicker',
    width: '2',
    height: '1',
    menutype:'other',
    index:'1',
    imgurl:require('../../../img/datepicker.png'),
  },
  {
    name: '文本框',
    type: 'label',
    width: '2',
    height: '1',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/label.png'),
  },
  {
    name: '进度条',
    type: 'probar',
    width: '3',
    height: '1',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/probar.png'),
  },
 
   {
    name: '表格',
    type: 'table1',
    width: '6',
    height: '5',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/table.png'),
  },
   {
    name: '选择器',
    type: 'select',
    width: '3',
    height: '1',
    menutype:'other',
    index:'1',
    imgurl:require('../../../img/select.png'),
  },
   {
    name: '按钮/文本',
    type: 'button',
    width: '3',
    height: '1',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/button.png'),
  }, 
  {
    name: '仪表盘',
    type: 'dashboard',
    width: '3',
    height: '2',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/dash01.png'),
  },
  {
    name: '温度计',
    type: 'temp',
    width: '3',
    height: '4',
    menutype:'base',
    index:'1',
    imgurl:require('../../../img/temp0001.png'),
  }

  
]
