module.exports={
	dataItem:[
		 {
	      id:'DS0',
	      url:'http://www.w3school.com.cn/example/jquery/demo_test.asp',
	      type:'get',
	      data:'',
	      edit:false
	    },
	     {
	      id:'DS0',
	      url:'http://www.w3school.com.cn/example/jquery/demo_test.asp',
	      type:'get',
	      data:'',
	      edit:false
	    },
	]
}